---
git:
  submodules:
    false
before_install:
  - git submodule update --init --recursive

install:
  - wget -O /tmp/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.52/hugo_0.52_Linux-64bit.deb
  - sudo dpkg -i /tmp/hugo.deb

script:
  - hugo

after_script:
  - rm -rf deployment
  - git clone -b master ${GH_REF} deployment
  - git init
  - git config user.name "${U_NAME}"
  - git config user.email "${U_EMAIL}"
  - git config --global push.default simple
  - rsync -av --delete --exclude ".git" public/ deployment
  - cd deployment
  - git add -A
  - git commit -m "rebuilding site on `date`, commit ${TRAVIS_COMMIT} and job ${TRAVIS_JOB_NUMBER}" || true
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}"
  - cd ..
  - rm -rf deployment

branches:
  only:
    - hugo