baseURL = "https://mryqu.github.io/"
languageCode = "zh-CN"
defaultContentLanguage = "zh"
title = "Mryqu's Notes"
theme = "next"

[Author]
  DisplayName = "mryqu"

[Params.Disqus]
  ShortName = "mryqu"

[Params.Share]
  Disqus = "mryqu"

[markup]
  [markup.goldmark]   
    [markup.goldmark.renderer]
      unsafe = true